version: "2"

services:
  ts3:
    build:
        context: ts3_query_server_test/
    ports:
        - "9987/udp"
        - "10011"
        - "30033"

  ts3-api:
    build: 
      context: ts3_query_http_api/
    links:
        - ts3:ts3

  haproxy:
    image: 'eeacms/haproxy'
    links:
     - ts3-api
    ports:
     - "9652:5000"
     - "1936:1936"
    environment:
      STATS_AUTH: "change:me"
      BACKENDS: "ts3-api"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
